version = 0.1
[default.deploy.parameters]
stack_name = "gym-equipment-stack"
resolve_s3 = true
s3_prefix = "gym-equipment-stack"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
